version: '3.1'

services:
  socat:
    image: jmb12686/socat
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "socat", "tcp-listen:2375,fork,reuseaddr","unix-connect:/var/run/docker.sock" ]

  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: none

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    logging:
      driver: none

  ytdl:
    image: bennythink/ytdlbot
    env_file:
      - env/ytdl.env
    restart: always
    depends_on:
      - socat
      - redis

  worker:
    image: bennythink/ytdlbot
    env_file:
      - env/ytdl.env
    restart: always
    command: [ "/usr/local/bin/celery" ,"-A","tasks","worker","--loglevel=info","--pool=prefork","--concurrency=200" ]
